### ISSUE TITLE
"There needs to be a permission in the app manifest."

### ISSUE THREAD

**Issue by Rory-Reid** [SoftPlay/SpheroWindows#2]
Upon pulling this, building it and connecting a Sphero and then running it on any machine other than David's, the app will fail to connect to the Sphero and the Visual Studio output window will display a very curious message:

"There needs to be a permission in the app manifest.
Add UUID of Sphero to manifest: 00001101-0000-1000-8000-00805F9B34FB"

I've not looked into this too much but this has been apparent on two separate systems now. @roadz99 if you want to work on figuring this out in person feel free to pester me!

From my small and limited research, I found [this file](https://github.com/lewisbenge/Sphero-WinPhone8-SDK/blob/master/RobotKit/RobotProvider.cs) in an open source port of the Sphero SDK which will trigger some logic that prints this line of output, verbatim. Maybe it'll shed some light, maybe it'll be unnecessary.

**Comment by DavidMartynWood** [comment]
Is your windows 10 in developer mode. Just a guess.

**Comment by DavidMartynWood** [comment]
This lead me to the sources code for the DLL I'm using so might try to
incorporate that instead of the library when I have time.

https://github.com/lewisbenge/Sphero-WinPhone8-SDK

**Comment by Rory-Reid** [comment]
Can confirm I'm in developer mode myself.

**Comment by DavidMartynWood** [comment]
Please try the latest code. I've reworked it to use a universal windows platform DLL to connect to sphero, instead of using a windows 8.1 DLL.

**Comment by Rory-Reid** [comment]
Yep, that's solved it! Even post-anniversary update!

**Comment by DavidMartynWood** [comment]
I had to rework the rfcomm API calls to make it work. I think maybe windows 10 anniversary update broke the rfcomm compatibility with windows 8.1 DLLs. Glad the basics are now working.
